<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ClientTest\SampleTest'                       => __DIR__ . '/tests/ClientTest/SampleTest.php',
    'ClientTest\Framework\TestCase'               => __DIR__ . '/tests/ClientTest/Framework/TestCase.php',
    'ClientTest\Controller\ConsoleControllerTest' => __DIR__ . '/tests/ClientTest/Controller/ConsoleControllerTest.php',
    'Client\Module'                               => __DIR__ . '/Module.php',
    'Client\Service\ZpkInvokable'                 => __DIR__ . '/src/Client/Service/ZpkInvokable.php',
    'Client\Controller\ZpkController'             => __DIR__ . '/src/Client/Controller/ZpkController.php',
);
