<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Client\Module'                               => __DIR__ . '/Module.php',
  'Client\Service\ZpkInvokable'                 => __DIR__ . '/src/Client/Service/ZpkInvokable.php',
  'Client\Service\PathInvokable'                => __DIR__ . '/src/Client/Service/PathInvokable.php',
  'Client\Controller\ZpkController'             => __DIR__ . '/src/Client/Controller/ZpkController.php',
  'Client\Controller\ApiController'             => __DIR__ . '/src/Client/Controller/ApiController.php',
  'Client\Controller\AppController'             => __DIR__ . '/src/Client/Controller/AppController.php',
  'Client\Controller\LibController'             => __DIR__ . '/src/Client/Controller/LibController.php',
  'Client\Controller\TargetController'          => __DIR__ . '/src/Client/Controller/TargetController.php',
);
