language: php

php:
  - 5.6
  - 7.0
matrix:
  include:
  - php: 5.3
    dist: precise

install:
  - composer install --prefer-source

before_script:
  - mkdir -p build/coverage

script:
  - vendor/bin/php-cs-fixer fix -v --dry-run --level=psr2 . 
  - vendor/bin/phpunit -c module/Client/tests/phpunit.xml --coverage-clover build/coverage/coverage.xml
  - php bin/zs-client.phar targetFileLocation 
  - php bin/build-zpk.php

after_script:
   # Check the code-coverage
   # - vendor/bin/coveralls -v

matrix:
  fast_finish: true
