name: Automatic Releases

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Setup PHP 7.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.1'

    - name: Environment
      run: |
        env

    - name: Get Source Code
      uses: actions/checkout@v2

    - name: Get Composer Dependencies
      run: |
        composer install --no-dev
        # Manually fix the zend-stdlib issue
        (cd vendor/zendframework/zend-stdlib/; patch -p1 < ../../../.patches/zend-stdlib.patch)

    - name: Build Phar file
      run: php -d phar.readonly=0 bin/create-phar.php

    - name: Build ZPK file
      run: php ./bin/build-zpk.php

    - name: "TODO: Push back the compiled Phar and ZPK to repository"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        DIFF=$(git diff)
        if [ -n "$DIFF" ]; then
          git config user.email "release@zend.com"
          git config user.name "Automated Release"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git commit -a -m "Update phar and zpk"
          git push
        fi